// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MottuMaintenance.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MottuMaintenance.Migrations
{
    [DbContext(typeof(MottuContext))]
    [Migration("20240904202518_EfficientMechanic")]
    partial class EfficientMechanic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MottuMaintenance.Models.ConsertoMoto", b =>
                {
                    b.Property<int>("ConsertoMotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConsertoMotoId"));

                    b.Property<int>("ComplexidadeDoConserto")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MecanicoId")
                        .HasColumnType("integer");

                    b.Property<int>("MotoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TempoReal")
                        .HasColumnType("integer");

                    b.Property<int>("TipoConsertoId")
                        .HasColumnType("integer");

                    b.HasKey("ConsertoMotoId");

                    b.HasIndex("MecanicoId");

                    b.ToTable("ConsertoMotos");
                });

            modelBuilder.Entity("MottuMaintenance.Models.Mecanico", b =>
                {
                    b.Property<int>("MecanicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MecanicoId"));

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<int>("NivelComplexidade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TempoPorDia")
                        .HasColumnType("integer");

                    b.HasKey("MecanicoId");

                    b.ToTable("Mecanicos");
                });

            modelBuilder.Entity("MottuMaintenance.Models.TipoConserto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TempoEstimado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TipoConsertos");
                });

            modelBuilder.Entity("MottuMaintenance.Models.ConsertoMoto", b =>
                {
                    b.HasOne("MottuMaintenance.Models.Mecanico", "Mecanico")
                        .WithMany("ConsertoMotos")
                        .HasForeignKey("MecanicoId");

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("MottuMaintenance.Models.Mecanico", b =>
                {
                    b.Navigation("ConsertoMotos");
                });
#pragma warning restore 612, 618
        }
    }
}
